name: Trigger Private CI
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: [ros2-hkr]

jobs:
  doTriggerPrivateCI:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == 'rebuild!') ||
      (github.event_name == 'pull_request_target') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-22.04
    timeout-minutes: 35
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_CLIENT_KEY }}

      - name: Trigger Build in Private Repo
        uses: dacbd/create-issue-action@v1.2.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: realsense-ros-private-ci
          title: CheckPublicPR
          body: ${{ github.event.pull_request.number }}

#ToDo:
# on the rebuild! comment, there's an issue with the sha pointing to something other than pr/merge,
#     therefore, for 'rebuild!' we need to take the sha from github.event, and not github.sha

#ToDo:
# manual trigger although present, does not work, as PR number is required

#ToDo:
# support running on tips of branches rather than on Pull Request

#ToDo:
# the rebuild!! comment trigger is not limited to the ros2-development branch
